server:
  port: 8080
  address: 0.0.0.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - http://127.0.0.1:3000
              - http://localhost:8080
              - http://127.0.0.1:8080
              - http://223.104.83.81:3000
              - https://wo1141777op6.vicp.fun
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: provider
          uri: lb://provider
          predicates:
            - Path=/api/**  # 请求路径匹配
