server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: provider

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 60000
ai:
  chat:
    base-url: http://127.0.0.1:8000
  asr:
    base-url: http://127.0.0.1:8000
  tts:
    base-url: http://127.0.0.1:8000